### ISSUE TITLE
Camera Detection Notification doesn't work for me

### ISSUE THREAD

**Issue by Cr4z33** [apollo1220/blueprints#14]
I've tried adding your automation to be used with a Tapo C310, but I get no notification (running the automation manually ends up the same way) at all on my mobile.

Device looks correct so maybe the sensor is not working somehow?

Automation:
```
alias: Persona rilevata
description: Rilevamento persone Tapo C310 (Avanti)
use_blueprint:
  path: apollo1220/camera_detection_notification.yaml
  input:
    notify_device: 573babd5445619779f6e7cc282a8b0e9
    camera: camera.tapo_c310_avanti_hd_stream
    person_sensor: select.tapo_c310_avanti_person_detection
    store_location: avanti
    no_motion_wait: 10
```

Camera person sensor:
![Screenshot 2024-07-01 at 11-27-53 Impostazioni – Home Assistant](https://github.com/apollo1220/blueprints/assets/19343851/cbc577ee-7559-4107-a34f-6129c0e6fe85)
